version: '3.8'
services:
  hotel-service:
    build:
      context: ./HotelService
    ports:
      - "5001:80"
    depends_on:
      - hotel-db
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=hotel-db;Port=5432;Database=hotelguide;User Id=admin;Password=password;

  report-service:
    build:
      context: ./ReportService
    ports:
      - "5002:80"
    depends_on:
      - report-db
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=report-db;Port=5432;Database=reportguide;User Id=admin;Password=password;

  hotel-db:
    image: postgres:15
    container_name: hotel-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotelguide
    ports:
      - "5432:5432"

  report-db:
    image: postgres:15
    container_name: report-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reportguide
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
